# Site
repository: junec1982/junec1982.github.io
favicon: images/favicon.ico

# Personal info
name: June Castillote
title: Office 365, Messaging & Collaboration Engineer
email: june.castillote@gmail.com
website: www.lazyexchangeadmin.com

# Social links
twitter_username: junecastillote
github_username:  junecastillote
# dribbble_username: jekyll
facebook_username: june.castillote
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: junecastillote
# pinterest_username: jekyll
# youtube_username: junecastillote
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is June and I work as a Messaging and Office 365 Consultant. I have worked at a number of companies since 2004 and gained technical, teamwork and leadership skills.
  
  I have experience working with technologies including Exchange, Lync/Skype, SharePoint, Azure, Office 365, DNS, and Active Directory.

  ---NO YET COMPLETE---

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
